version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: animal-test
    ports:
      - "8082-8086:8081"
    volumes:
      - /home/sysdist-1/practicaParcialDist/test/data:/app/data
    deploy:
      replicas: 5
    networks:
      - my-network

  loadbalancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network
    depends_on:
      - app

networks:
  my-network:
    driver: bridge

